import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logoWrapper}>
          <Image
            className={styles.logo}
            src="/logo.svg"
            alt="Logo"
            width={32}
            height={26}
          />
        </div>
        <div className={styles.loginWrapper}>
          <h1 className={styles.header}>Login</h1>
          <input
            className={styles.emailInput}
            type="email"
            required
            placeholder="Email address"
          />
          <input
            className={styles.passwordInput}
            type="text"
            required
            placeholder="Password"
          />
          <button className={styles.loginButton}>Login to your account</button>
          <div className={styles.createAccountLinkWrapper}>
            <p className={styles.createAccountLinkDescription}>
              {"Don't have an account?"}
            </p>
            <Link href="/">
              <a className={styles.createAccountLink}>Sign Up</a>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
