import type { NextPage } from 'next'
import Head from 'next/head'
import LoginForm from '../components/ui/LoginRegisterForm/LoginRegisterForm'
import MovieItem from '../components/ui/MovieItem/MovieItem'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MovieItem />
      </main>
    </div>
  )
}

export default Home
